# Generated by Django 4.2.26 on 2025-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billingCycle',
            field=models.CharField(default='Dec25', max_length=50),
        ),
    ]
