# Generated by Django 4.2.26 on 2025-12-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billingcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='fullName',
            field=models.CharField(max_length=24),
        ),
    ]
