# Generated by Django 4.2.26 on 2025-12-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_billingcycle_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='daysInCycle',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='displayName',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='fullName',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='billingCycle',
            field=models.CharField(max_length=50),
        ),
    ]
