# Generated by Django 4.2.26 on 2025-12-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billingcycle_daysincycle_billingcycle_displayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='displayName',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='dueDate',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='endDate',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='fullName',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='startDate',
            field=models.DateField(null=True, unique=True),
        ),
    ]
