# Generated by Django 4.2.26 on 2026-03-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_billingcycle_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='billingCycle',
        ),
        migrations.AddField(
            model_name='transaction',
            name='billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.billingcycle'),
        ),
    ]
