# Generated by Django 4.2.26 on 2026-03-03 00:13

from django.db import migrations

def backfill_billing_cycle(apps, schema_editor):
    Transaction = apps.get_model('core', 'Transaction')
    BillingCycle = apps.get_model('core', 'BillingCycle')

    for txn in Transaction.objects.all():
        cycle = BillingCycle.objects.filter(
            startDate__lte=txn.date,
            endDate__gte=txn.date
        ).first()
        if cycle:
            txn.billing_cycle = cycle
            txn.save()
        else:
            # Optional: log or handle missing cycles
            print(f"No billing cycle for transaction {txn.id}")



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transaction_billingcycle_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_billing_cycle)
    ]
