# Generated by Django 4.2.26 on 2026-03-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('weekend', models.IntegerField()),
                ('monthName', models.CharField(max_length=10)),
                ('weekdayName', models.CharField(max_length=10)),
                ('isWeekend', models.BooleanField()),
            ],
        ),
    ]
