# Generated by Django 4.2.26 on 2026-03-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='weekend',
        ),
    ]
