# Generated by Django 4.2.26 on 2026-03-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_date_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='id',
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.date'),
        ),
    ]
