# Generated by Django 4.2.26 on 2026-03-13 18:36

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_date_id_alter_date_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('period', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('startDate', models.DateField(default=core.utils.get_today)),
                ('endDate', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.ForeignKey(default=core.utils.get_today, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.date'),
        ),
    ]
